# fly.toml app configuration file generated for html-to-adf on 2023-11-05T00:04:57+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "html-to-adf"
primary_region = "syd"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
